#!/bin/sh

set -e

case "$1" in
    install|upgrade)

	# If new debconf package installs, it may reset our noninteractive setting.
	# This may result in things like wireshark prompting the user about dumpcap privs.
	# Re-apply the noninteractive setting so that soup can proceed unattended.
	echo "debconf debconf/frontend select noninteractive" | debconf-set-selections || echo "Unable to set debconf to noninteractive!"

    ;;

    abort-upgrade)

    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
